travis:
  secure:
    BINSTAR_TOKEN: KZs8uKlR4BijvpRSzsBz9znD8nbXlqOD+1zyczxVTx33aAQ2jXyrI6mFtacpMEjMyyoGG3IjpIkrB/Nch0CcRlp9CfE6PAd0w7fQmvHMQMhI5U5Jg8ldDFWwcPj/36FFA0Rk8/D+gtBd7jfvSUjW8y8DPssCeWf0IS7aMbebj49myHsbEyXQ+EkuJQDEUFYCU7EO6j09ietRxZqcECEZVFGy9DoLVXT4LF/vPCmMjBVTad8RjX1luOWkHwM6L1re6vfoso/8BWdT589EuQ0ypanQma8si/xHqnEbKUXXni4QiXSiquGylVS0cTRcydfbvgHDJwytps6z3zBniZdvD14LFTTm5j8hyBCsvlKNBtUvuzowfo+EYRkRgKRJLK5zeVfiwiWIkmUix1yQYpFmhNChlrPesRy27FPy3bv4rCoJ6PDMAhL0MCqHqRaOOOq65CVOakeQgqnR/L2i3d5gn1ctuBVKZ8gSw8h0t8waVBV+JSZhlcvQf00asiDqj8dXxwCxxhfx8NriNmEhyAkJzw97R7hmvl9UVSI6/RW+XLanQkZ+zFoW0wXN4UVS/OhquBed6aBPeAgoqb8h37m/t2OSFXik7DNr2AuqMOMcG+rT46NsXMYsbj5f0Mr6nEXRrLzHO34DVnHFVXdMH5k3g3K+gqJRqKa1yg9LPJT891Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
